### ISSUE TITLE
Upgrading diesel_cli 

### ISSUE THREAD

**Issue by harinimaniam** [krsmanian1972/ferries#1]
This is the solution to upgrade diesel_cli:

1. brew update
2. brew upgrade

Then run:
cargo install diesel_cli --no-default-features --features "mysql"

**Comment by krsmanian1972** [comment]
Our database is MySql. I faced the infamous image not found "libpq.5.dylib" since the cli thinks that I'm using postgres.
Reinstalling the diesel cli solved my problem.
